### ISSUE TITLE
[1.20.1] Ore Hammers only have one use

### ISSUE THREAD

**Issue by Zedrimar** [Lemon-Juiced/LemonCore#1]
Ore hammers currently derped and only have one use. Sadly, my brain was only half functioning the last few weeks so it took me way too damn long to report this.

lemon core: 1.20.1-1.0.39
Neoforge: 47.1.79

**Comment by Lemon-Juiced** [comment]
I'll look into it, it seemed to be working fine when I last looked but it they mightve broke with a more recent update somehow.

**Comment by Zedrimar** [comment]
Also, I tested this in a test instance with just a few mods and yep, still broken. Had to test to make sure I wasn't just going crazy since I uh.... Yeah my main modded instance has 500 mods....

**Comment by Lemon-Juiced** [comment]
500 mods... calm down. That's almost too much. I'm not 100% certain what went on yet, but I also didn't really get to spend any time looking at it tonight like I planned because the Five Nights at Freddys movie came out and needless to say I got sidetracked. It'll be fixed as soon as possible.

**Comment by Lemon-Juiced** [comment]
This should have been fixed in the latest commit. So somehow every word "tag" in the ore_crushing_hammers folder became replaced with the word "gems". I have no clue how, but the issue has been resolved now.

**Comment by Zedrimar** [comment]
Awesome, thank you!

**Comment by Zedrimar** [comment]
Ok soooo that didn't fix it apparently... I updated the mod and it still only gives the hammers one use whenever they are used. I don't know if it helps, but it may or may not be useful to look at how the allthemodium mod handles their ore hammer recipes. The game still keeps acting as if it needs to just consume the item rather than taking durability off it.

Logs:
https://pastebin.com/M52X900k (latest log on test instance)
https://pastebin.com/TWg0pet4 (debug log)

Maybe implement a check during crafting to first calculate durability needed to be reduced from the ore hammer, craft X number of dust based off how much durability is left on the ore hammer and then leave the ore hammer in the crafting grid like a bucket would be left after a water or lava recipe? Well, unless that was already implemented but minecraft is being stupid in execution of it. I don't know, my coding knowledge is very small at the moment. That's how I would do it anyway.

**Comment by Lemon-Juiced** [comment]
So its working for me in my test instance as intended. The hammer recipes are all handled through JSON so it has nothing to do with the java. Are you on 1.0.40?

**Comment by Zedrimar** [comment]
Yeah, that's what I have installed right now. Unless it's some kind of weird mod interaction thing. My main modded world I was using neoforge 47.1.79, test instance originally had Forge 47.1.47. I then updated regular forge to 47.2.1 in case it was something with forge, but nope, still same thing.

Here's what I have loaded on the test instance. Though I even tried limiting this to just (latest versions of) JEI, Lemon Core, Scalar utils (I was still messing with that one in a creative world) and curios API because scalar utils requires it. Same issue. Ore hammer used once and poofs. Used netherite ore hammer for testing with obsidian and iron.
![image](https://github.com/Lemon-Juiced/LemonCore/assets/8153290/ea169235-7b14-4d3a-9a9f-a35a553f18ed)

Issues persisted regardless of what forge version I used, whether neoforge or regular forge. Not sure if that has anything to do with it.

**Comment by Lemon-Juiced** [comment]
Okay so as it turns out then, thats an unrelated issue to the last. I have no clue why they're broken in two spots but ill release a patch today.

**Comment by Lemon-Juiced** [comment]
So the issue wasn't what I thought it was, I believe the issue is resolved but my IntelliJ has been giving me issues all day so hopefully it works.

**Comment by Zedrimar** [comment]
Ah, IntelliJ.... My favorite IDE, while simultaneously occasionally a pain in the ass. Well, you know what they say, if it can break, it will break. Er.... something like that.... Maybe that's just my motto.

Anyway.... After testing, it finally works! Not sure if they are supposed to have no durability taken from them, but I don't care, overpowered or not, I'll take it! At least it finally works, and all my sacrificed netherite hammers will not be in vain!
